### ISSUE TITLE
Unexpected behaviors when default value is provided

### ISSUE THREAD

**Issue by nuragic** [fraserxu/react-dropdown#14]
Hi,

I'm experiencing unexpected behaviors when changing dropdown values. It only happens when the component is initialized with a default value.

Example:

```jsx

// ...
const options = [
    { value: 20,   label: 'Show 20' },
    { value: 50,   label: 'Show 50' },
    { value: 100,  label: 'Show 100'}
];

// ...

render()  {

  return(
    <Dropdown
      value={options[0]}
      options={options}
    />
  );

}
```

When I select an option (that is not the default one), the first time works as expected, but the second time it fails to show the corresponding label, showing the default one.

I tried to pass an integer as an alternative value but it doesn't work.

Thanks!

**Comment by huchenme** [comment]
+1

**Comment by fraserxu** [comment]
You have to had a click handler in your code to change the state.

```JavaScript
<Dropdown options={options} onChange={this._onSelect.bind(this)} value={defaultOption} />
```

And then

```JavaScript
  _onSelect(option) {
    console.log('You selected ', option.label)
    this.setState({selected: option})
  }
```
