### ISSUE TITLE
parseValue should be used in componentWillReceiveProps

### ISSUE THREAD

**Issue by tamias** [fraserxu/react-dropdown#141]
I see that there was a recent change that added `parseValue`, which is used to set the `selected` state of the component in the constructor.  This is a nice improvement.

I believe `parseValue` should also be used when setting the `selected` state in `componentWillReceiveProps`.

I want the Redux form field's value to be just the value, rather than an object containing the label and the value, so I am using a normalize function: `normalize: ({ value }) => value`.  Unfortunately, this means that the placeholder shows the value instead of the label.

**Comment by fraserxu** [comment]
Fixed in #141
