### ISSUE TITLE
 I use the dropdown in react js app but onChange is not triggering  

### ISSUE THREAD

**Issue by abdulkadhir** [fraserxu/react-dropdown#147]
I use the dropdown in react js app but onChange is not triggering

my code is:

   
  

    import React from "react";
    import PropTypes from "prop-types";
    import Dropdown from 'react-dropdown';
    const options = [
       { value: 'one', label: 'One' },
       { value: 'two', label: 'Two', className: 'myOptionClassName' },

    ];

    class WebDashboardPage extends React.Component {

     constructor(props) {
     super(props);
     this.state = { value:''}
    this.quan = this.quan.bind(this);
    }

     quan = (event)=> {
     console.log("Option selected:");
    this.setState({ value: event.target.value });
 
     };

     render() {

      return(
       <b><Dropdown className="dropdownCss" options={options} onChange={e => 
       this.quan(e.target.value)} /></b>
      );

     }

It shows the error
TypeError: Cannot read property 'quan' of undefined

**Comment by fraserxu** [comment]
I think this is because you are using `this` inside the onChange handler

```JavaScript
// `this` here is in the scope of this callback function, not the class anymore
onChange={e => this.quan(e.target.value)} 
```

Instead you only need

```JavaScript
<b><Dropdown className="dropdownCss" options={options} onChange={this.quan} /></b>
```

**Comment by fraserxu** [comment]
See here for an online example I just created https://codesandbox.io/s/94mpk3o654
