### ISSUE TITLE
Remove babel configuration from built npm module package.json

### ISSUE THREAD

**Issue by renegare** [fraserxu/react-dropdown#149]
Could you please remove your babel config from your built package.json which is published to npm.

Ideally simply move the it into a .babelrc file in the root of your directory.

```
  "babel": {
    "presets": [
      "react",
      "es2015",
      "stage-0"
    ]
  },
```

The issue is when consuming your package (which is great package 👍), having your babel inside your package.json sadly enforces that I install the presets you have defined, which I don't need because ... well your module comes precompiled in npm.

To demonstrate; clone this test repo:
https://github.com/renegare/babel-react-dropdown-issue

and run the following commands:
```
npm i
npm run build
```

You will get an error.

Steps to fix (dirty):
* To resolve; look for the following file in the `node_modules` folder; `./node_modules/react-dropdown/package.json`
* remove the `babel` config and save the file
* re-run `npm run build`

---

I believe this is a bug with babel and I have not tested this with babel 7. I just noticed other modules I use *do not* have babel config within their built package.json modules e.g. react

Also bable documentation is mute on the pros and cons of including bable config in package.json.

Great to here your thoughts and happy to push a PR.

💪🏾

**Comment by fraserxu** [comment]
Ah I see why your build is failing. Normally for a project using webpack, you do not want to let Babel compile code from `node_modules` again as the code there has already been compiled by Babel before publishing(I think this is also true for any other React component on NPM). 


To fix the issue, you can put `exclude: /node_modules/` in the babel loader.

**Comment by renegare** [comment]
excellent point. Will check that too.

**Comment by renegare** [comment]
Closing this issue:

* Neither here nor there if its good / bad practise to keep babel config in npm module pkg. 
* @fraserxu makes a good point. Webpack configuration can exclude babelfying dependant code
* happy days 💪🏾
