### ISSUE TITLE
tabIndex prop doesn't seem to be working

### ISSUE THREAD

**Issue by DanielJBailey** [fraserxu/react-dropdown#156]
When tabbing through my form, my tab key skips right over my DropDown form even with an included `tabIndex` attribute. Any suggestions how to remedy this issue? I am using a Mac and chrome.

**Comment by aaron-thompson** [comment]
I get a warning that is probably related to your problem.  It is likely an easy to fix typo.

Warning: Invalid DOM property `tabindex`. Did you mean `tabIndex`?
    in div (created by Dropdown)...

**Comment by DanielJBailey** [comment]
@aaron-thompson I've tried that already, but it is still skipping over my dropdown menu's when I tab through a form. 

`<Dropdown
                  name="app_title"
                  options={titles}
                  value={app_title}
                  required
                  onChange={this.handleTitleSelect}
                  placeholder="Job Title"
                  tabIndex="1" // tabIndex={1}
               />`

**Comment by fraserxu** [comment]
Published to `+ react-dropdown@1.6.4`
