### ISSUE TITLE
Can't use with Babel 7 and parcel-bundler

### ISSUE THREAD

**Issue by susemeee** [fraserxu/react-dropdown#179]
```
Plugin/Preset files are not allowed to export objects, only functions.
In C:\Users\user\source\parcel\node_modules\react-dropdown\node_modules\babel-preset-react\lib\index.js
```

Because package.json explicitly requires Babel 6(and old presets) and parcel-bundler depends on package.json, the preset conflicts with Babel 7.

Upgrading transpiler to 7.x might be helpful.

**Comment by smeevil** [comment]
Is there anything blocking the merge ? Looking forward to this :)
