### ISSUE TITLE
Customizing class names

### ISSUE THREAD

**Issue by paulmelnikow** [fraserxu/react-dropdown#2]
Hi there, thanks again for this great component.

I'd like to customize the class names emitted by the component. I'm building an embedded component, which is an area where React really shines.

One of my goals is to protect my content from the integrator's style sheets, so I can better accomplish that by using unique class names – basically prefixing everything, like `mycomponent-dropdown-component` etc.

Another advantage to letting the user customize the class names is that it becomes easier to integrate the component with an existing set of styles, such as when migrating an existing app, or having this component coexist on a page with dropdowns built in some other way.

Would you be interested in a PR that pulls the class names from props? They could default to the names you're using now.

**Comment by fraserxu** [comment]
Sure. I think it's a good idea to always have an option for the component. 

And I agree with you that the class name should be allowed to customize.

It would be great if you can send me a pull request(in case you need it now), or I can do it by myself later today.

**Comment by ericdfields** [comment]
+1… I'll do a PR if I can muster the energy :)

**Comment by thebigredgeek** [comment]
Bump?
