### ISSUE TITLE
Getting a deprecated findDOMNode warning

### ISSUE THREAD

**Issue by micahblu** [fraserxu/react-dropdown#201]
I'm getting this warning on version 1.8.0

index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Dropdown which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node

**Comment by fraserxu** [comment]
Fixed in https://github.com/fraserxu/react-dropdown/pull/204
