### ISSUE TITLE
How to reset default value after option has been selected.

### ISSUE THREAD

**Issue by BigDaddyKahuna** [fraserxu/react-dropdown#212]
It appears that once you select an option from the dropdown, that value remains selected. I would like to reset the value to the default value after capturing the user's selection. Is this possible?

**Comment by ordidxzero** [comment]
```
const [otherValue, setOtherValue] = useState('');
const [value, setValue] = useState<string | undefined>(undefined);
  useEffect(() => {
    setValue(undefined);
  }, [selectedSpeechId]);

...

<Dropdown value={value} />

```

**Comment by freder** [comment]
`<Dropdown value={undefined} />` does not seem to work. – selecting an option will still update the state.
