### ISSUE TITLE
Dropdown "breaks" when using <Number> values

### ISSUE THREAD

**Issue by IanCStewart** [fraserxu/react-dropdown#220]
The Dropdown component stays empty when using values typed as number.

For example:
```jsx
const [dropdownValue, setDropdownValue] = useState(32);

const dropdownOptions = [
    { label: "32", value: 32 },
    { label: "64", value: 64 },
    { label: "96", value: 96 },
    { label: "128", value: 128 },
    { label: "160", value: 160 },
    { label: "192", value: 192 },
    { label: "224", value: 224 },
    { label: "256", value: 256 },
    { label: "288", value: 288 },
    { label: "320", value: 320 },
    { label: "352", value: 352 },
    { label: "384", value: 384 }
  ];
 
// render
<Dropdown
    options={dropdownOptions}
    value={dropdownValue}
    onChange={(option) => setDropdownValue(option.value)}
    placeholder="Choose number"
/>
```
 with value set to 32 will render an empty dropdown. Opening the menu works as well as updating state to the new value. But the dropdown always shows empty. (see image below)
 
<img width="629" alt="image" src="https://user-images.githubusercontent.com/14125280/115257848-c3c67f00-a130-11eb-94ce-67fa05b9d400.png">

I have attached a sandbox with the code example to show the issue.

[![Edit serene-firefly-kcmtq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/serene-firefly-kcmtq?fontsize=14&hidenavigation=1&theme=dark&view=preview)

**Comment by Jay47777** [comment]
Try this code.


const dropdownOptions = [
    { label: "32", value: "32" },
    { label: "64", value: "64" },
    { label: "96", value: "96" },
    { label: "128", value: "128" },
    { label: "160", value: "160" },
    { label: "192", value: "192" },
    { label: "224", value: "224" },
    { label: "256", value: "256" },
    { label: "288", value: "288" },
    { label: "320", value: "320" },
    { label: "352", value: "352" },
    { label: "384", value: "384" }
  ];

**Comment by IanCStewart** [comment]
> Try this code.
> 
> const dropdownOptions = [
> { label: "32", value: "32" },
> { label: "64", value: "64" },
> { label: "96", value: "96" },
> { label: "128", value: "128" },
> { label: "160", value: "160" },
> { label: "192", value: "192" },
> { label: "224", value: "224" },
> { label: "256", value: "256" },
> { label: "288", value: "288" },
> { label: "320", value: "320" },
> { label: "352", value: "352" },
> { label: "384", value: "384" }
> ];

Yes I'm aware that this code would work but that's not the issue I'm trying to convey.

The problem is that if you use a value of `Type<Number>` the dropdown should still work.

**Comment by Carlos-Gaxiola** [comment]
Hello, can I work on this?

**Comment by BenGunnewijk** [comment]
Your usestate should initialize the default value as 

const [dropdownValue, setDropdownValue] = useState({label: "32", value: 32});

on line six of your codesandbox.

**Comment by IanCStewart** [comment]
@BenGunnewijk Thanks for the reply! Looked into it and setting the default state as an object and then onChange using the full object again seems to do the trick.

```jsx
const [dropdownValue, setDropdownValue] = useState({ label: "32", value: 32 });

const dropdownOptions = [
    { label: "32", value: 32 },
    { label: "64", value: 64 },
    { label: "96", value: 96 },
    { label: "128", value: 128 },
    { label: "160", value: 160 },
    { label: "192", value: 192 },
    { label: "224", value: 224 },
    { label: "256", value: 256 },
    { label: "288", value: 288 },
    { label: "320", value: 320 },
    { label: "352", value: 352 },
    { label: "384", value: 384 }
  ];
 
// render
<Dropdown
    options={dropdownOptions}
    value={dropdownValue}
    onChange={(option) => setDropdownValue(option)}
    placeholder="Choose number"
/>
```
