### ISSUE TITLE
React 18 Support.

### ISSUE THREAD

**Issue by bsabhi** [fraserxu/react-dropdown#241]
is react 18 support scheduled for this library? any feedback is appreciated. thanks.

**Comment by onderbakirtas** [comment]
I'm using it on my last project which has NextJS v12.3 and ReactJS v18.2. I'm curious about the support you are mentioning. There are incorrect peer dependency warnings those should be updated, though.

**Comment by bsabhi** [comment]
you are right @onderbakirtas it is working fine with react 18. but it does break our CI flow when installing packages because of those peer dependencies warnings, so we have to add  --legacy-peer-deps flag every time.

**Comment by onderbakirtas** [comment]
Last commit was on Apr 27, don't know if this is actively maintained at the moment. It needs someone to get their hands dirty.  🤔

**Comment by fraserxu** [comment]
Sorry for the delay, just published to `v1.11.0` with `peerDependency` updated to support React 18. https://www.npmjs.com/package/react-dropdown/v/1.11.0
