### ISSUE TITLE
Dropdown doesn't open

### ISSUE THREAD

**Issue by mastertinner** [fraserxu/react-dropdown#36]
Has anything changed about the configuration of the component since `0.7.2`? My dropdown used to work fine with `0.7.2` but since I upgraded to `1.0.2`, it doesn't open anymore. Unfortunately there's no error message at all so I cannot imagine what the problem might be...

The "caret" on the right side of the dropdown actually turns upside down but then the options are not shown.

**Comment by fraserxu** [comment]
That is strange, I had no issue on my side. There's an example in the [example](https://github.com/fraserxu/react-dropdown/tree/master/example) directory, can you check you have the correct configuration? Or can you try to run the example locally please?

**Comment by ahstro** [comment]
I'm not 100%, but this could have something to do with changing the class of the root node from `Dropdown` to `Dropdown-root`. When I first made the change, I forgot to change the CSS selector, causing the root node to not have `position: relative;`, so the absolutely positioned menu ended up in a strange place..

**Comment by fraserxu** [comment]
@ahstro I have no issue running the example though. Will double check tonight.

**Comment by ahstro** [comment]
@fraserxu I was thinking that maybe @mastertinner had something with their setup that messed with the `position`s. Not sure what that could be, but I thought it was worth mentioning :)

**Comment by mastertinner** [comment]
@ahstro, your guess was absolutely correct. I had set the `.Dropdown-menu`'s position to `absolute`. Thanks a lot!!
