### ISSUE TITLE
placeholder instead of selected label after re-render

### ISSUE THREAD

**Issue by wojciech-panek** [fraserxu/react-dropdown#43]
There is a bug in index.js:23 in componentWillReceiveProps

there should be:

`} else if (!newProps.value && newProps.placeholder) {`

instead of:

`} else if (newProps.placeholder) {`

In current implementation if first if-condition is resolved as false because values are equal and placeholder is given result will be the placeholder label. In other words, even if other value was selected before Dropdown resets to placeholder.

It can be quickfixed by passing to placholder attribute:

`placeholder={selectedValue || 'Placeholder label'}`

**Comment by episodeyang** [comment]
Is this repo still maintained? I'm running into this same issue.

**Comment by fraserxu** [comment]
Published to react-dropdown@1.0.4
