### ISSUE TITLE
is-selected doesn't seem to be getting set

### ISSUE THREAD

**Issue by Zashy** [fraserxu/react-dropdown#54]
When rendering the is-selected class onto an option it never seems to be working. The line responsible seems to be comparing two separate objects, so is always returning false. Should be checking `option.value === this.state.selected.value` or perhaps even the value and the label.

Relevant lines:

```
    let optionClass = classNames({
      [`${this.props.baseClassName}-option`]: true,
      'is-selected': option === this.state.selected
    })
```

**Comment by fraserxu** [comment]
https://github.com/fraserxu/react-dropdown/pull/138
