### ISSUE TITLE
Click (tap) is propogated to underliying elements

### ISSUE THREAD

**Issue by miraage** [fraserxu/react-dropdown#56]
![image](https://cloud.githubusercontent.com/assets/971735/16724516/c25c0eac-475b-11e6-88e6-d6b336d5563c.png)

Upon selecting an option via device emulation mode, the button receives click event.
How do I figure this out?

**Comment by michaeltrim** [comment]
Also having this problem, was there a solution?

**Comment by miraage** [comment]
@michaeltrim no way but hack with manual `event.stopPropagation()`.

**Comment by michaeltrim** [comment]
@fraserxu why is the setValue called from option onMouseDown and onClick?
