### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by AndrewRayCode** [fraserxu/react-dropdown#75]
Lol, really?

    standard: Use JavaScript Standard Style (http://standardjs.com)
        react-dropdown/index.js:5:47: Extra semicolon.
    npm ERR! Test failed.  See above for more details.

**Comment by fraserxu** [comment]
?

**Comment by AndrewRayCode** [comment]
Clone this project and run npm install

**Comment by fraserxu** [comment]
Published to v1.2.1
