### ISSUE TITLE
Bug with dropdown when newProps.value == this.state.selected

### ISSUE THREAD

**Issue by lstorey** [fraserxu/react-dropdown#88]
In index.js: 
 componentWillReceiveProps (newProps) {
    if (newProps.value && newProps.value !== this.state.selected) {
      this.setState({selected: newProps.value})
    } else if (!newProps.value && newProps.placeholder) {
      this.setState({selected: { label: newProps.placeholder, value: '' }})
    } else {
      this.setState({selected: { label: DEFAULT_PLACEHOLDER_STRING, value: '' }})
    }
  }

This code incorrectly falls back to the default placeholder string when newProps.value == this.state.selected. It is causing a bug where the default placeholder string renders instead of the value when the dropdown rerenders.

**Comment by fil090302** [comment]
@fraserxu any plans on correcting this? looks like an easy fix and it's quite annoying :)

@lstorey pls fix the indentation on the code to keep the styling and to be a quicker merge.

**Comment by RobinJayaswal** [comment]
@fraserxu sorry to bug, but would be great to see this simple pr merged

**Comment by fraserxu** [comment]
Merged and published to v1.2.3 , sorry for the delay.
