### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by zhenyanghua** [fraserxu/react-dropdown#92]
Please update to react 1.5.4 and fix the dependencies.

**Comment by fraserxu** [comment]
@zhenyanghua would you mind create a pull request for this following this example? https://github.com/fraserxu/react-chartist/pull/50

**Comment by zhenyanghua** [comment]
My bad - just checked your code, and it turned out not using any `PropType` validations. No need to upgrade the peer dependencies nor add prop-types as a dependency.
