### ISSUE TITLE
onFocus callback missing - should not be an error

### ISSUE THREAD

**Issue by infomiho** [fraserxu/react-dropdown#93]
Latest version with this commit https://github.com/fraserxu/react-dropdown/commit/b2e669055c592452fe9d4965e39c8deae35d9dca#diff-168726dbe96b3ce427e7fedce31bb0bc
require from the user to specify the onFocus callback.

We should first check if it's present in order to prevent raising an error (like it is the case with onChange callback)

**Comment by fraserxu** [comment]
Thanks for report, @infomiho can you create a pull request for this?

**Comment by fraserxu** [comment]
Fixed in #94
