### ISSUE TITLE
Selected option not highlighted

### ISSUE THREAD

**Issue by ziveo** [fraserxu/react-dropdown#99]
I am using this module and it is really excellent.

The only feature that I am missing is to have selected option highlighted in Dropdown-menu.

How can that kind of functionality be accomplished?

**Comment by pankaja92** [comment]
@ziveo , Did you get this working ? Were you able to highlight the selected option ?

**Comment by fraserxu** [comment]
https://github.com/fraserxu/react-dropdown/pull/138
